spring.application.name=timeseries-writer
eureka.client.register-with-eureka=false
eureka.client.enabled=false
server.port=8080


# ===========================
# Kafka Producer Configuration
# ===========================
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional (recommended)
# spring.kafka.producer.properties.spring.json.add.type.headers=true


# ===========================
# Kafka Consumer Configuration
# ===========================
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Let Spring Kafka know which packages are safe for deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.backend.timeseries_writer.dto

# If you want to consume List<DataFormat> directly (no need for headers)
spring.kafka.consumer.properties.spring.json.use.type.headers=false

#receiving one record whose VALUE is a JSON array
spring.kafka.listener.type=single



# Tell JsonDeserializer the container and element type
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.ArrayList
spring.kafka.consumer.properties.spring.json.value.value.type=com.backend.timeseries_writer.dto.DataFormat

spring.kafka.consumer.group-id=data-group
spring.kafka.bootstrap-servers=broker:9092

## INFLUXDB
influx.url=http://database:8086
## all volumes will be uploaded on github there is no point in hiding the token in .secrets and .gitignore-ing it
#influx.token= E8FuNNUnUfu9_JzKM3SUnQ8k-Nonjo2J-gjuNUIW_g-1d3d8dByyxVivlhQQKjGTbMBtspWOlg-rWZ1bx4I5QA==  #DOCKER
#K8S below
influx.token= kAqU7bMn2-_nIauWStuMmkm10meUF765umKip4FJmuxgKaLbbtOIsP7MZ7oEpMPjUL5cAaOxzGhNaso0945wkg==
influx.org= org
#name of bucket ("database") is bucket 
influx.bucket= bucket
