apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeseries-writer
  template:
    metadata:
      labels:
        app: timeseries-writer
    spec:
      containers:
      - name: timeseries-writer
        image: timeseries-writer
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
