spring.application.name=read-api
eureka.client.register-with-eureka=false
eureka.client.enabled=false
logging.level.root=INFO

## Keycloak
# https://medium.com/@iaravinda33/integrating-keycloak-authentication-with-spring-boot-a-complete-guide-98df2c8d244a
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/api-gateway

## Zones Service Route
# 1) /api/v1/zone/{id}  -> zones-service
spring.cloud.gateway.server.webflux.routes[0].id=zones-get-by-id
spring.cloud.gateway.server.webflux.routes[0].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/zone/{id}
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api/v1/zone/(?<id>.*), /api/v1/zone/${id}

# 3) /api/v1/zone/get/ids  -> zones-service
spring.cloud.gateway.server.webflux.routes[1].id=zones-get-ids
spring.cloud.gateway.server.webflux.routes[1].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/zone/get/ids
#spring.cloud.gateway.server.webflux.routes[1].filters[1]=SetPath=/api/v1/zone/get/ids

# 3) /api/v1/zone  -> zones-service
spring.cloud.gateway.server.webflux.routes[2].id=zones-base
spring.cloud.gateway.server.webflux.routes[2].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/zone
#spring.cloud.gateway.server.webflux.routes[0].filters[2]=SetPath=/api/v1/zone


## Zone Thresholds Route

spring.cloud.gateway.server.webflux.routes[3].id=zone-threshold-get-by-id
spring.cloud.gateway.server.webflux.routes[3].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/zone/threshold/{id}

spring.cloud.gateway.server.webflux.routes[4].id=zone-threshold-base
spring.cloud.gateway.server.webflux.routes[4].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/zone/threshold


## Nodes Service Route

spring.cloud.gateway.server.webflux.routes[5].id=nodes-get-by-id
spring.cloud.gateway.server.webflux.routes[5].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/node/{id}

spring.cloud.gateway.server.webflux.routes[6].id=node-get-ids
spring.cloud.gateway.server.webflux.routes[6].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/node/get/ids

spring.cloud.gateway.server.webflux.routes[7].id=node-base
spring.cloud.gateway.server.webflux.routes[7].uri=http://zones-service:8080
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/node

