spring.application.name=aggregation-service
spring.docker.compose.enabled=false
server.port=0
springdoc.swagger-ui.path=/swagger-ui.html

## INFLUXDB
influx.url= http://localhost:8083
## all volumes will be uploaded on github there is no point in hiding the token in .secrets and .gitignore-ing it
influx.token= E8FuNNUnUfu9_JzKM3SUnQ8k-Nonjo2J-gjuNUIW_g-1d3d8dByyxVivlhQQKjGTbMBtspWOlg-rWZ1bx4I5QA==
influx.org= org
#name of bucket ("database") is bucket 
influx.bucket= bucket
