apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080


# kubectl get pods -l app=api-gateway
# kubectl logs api-gateway-5f6c8d9b9b-abc12
