apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080


# Expose API Gateway

# kubectl apply -f api-gateway-nodeport.yaml


# kubectl get svc
# http://localhost:30080/index.html

