spring.application.name=ingest-service
server.port=8080
eureka.client.register-with-eureka=false
eureka.client.enabled=false

springdoc.swagger-ui.path=/swagger-ui.html

#no need for eureka.client.service-url on default zone


# ===========================
# Kafka Producer Configuration
# ===========================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional (recommended)
spring.kafka.producer.properties.spring.json.add.type.headers=true


# ===========================
# Kafka Consumer Configuration
# ===========================
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Let Spring Kafka know which packages are safe for deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.backend.ingest_service.dto

# If you want to consume List<DataFormat> directly (no need for headers)
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.List<com.backend.ingest_service.dto.DataFormat>

# (optional but helpful)
spring.kafka.consumer.group-id=data-group
spring.kafka.bootstrap-servers=broker:9092
#container name : listener port