apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-api
spec:
  selector:
    matchLabels:
      app: read-api
  template:
    metadata:
      labels:
        app: read-api
    spec:
      containers:
      - name: read-api
        image: read-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
