apiVersion: v1
kind: Service
metadata:
  name: ingest-service
spec:
  selector:
    app: ingest-service
  ports:
    - port: 8080
      targetPort: 8080



# kubectl apply -f ingest-service.yaml
# kubectl get svc

# TEST CONNECTIVITY :

# kubectl run test --rm -it --image=curlimages/curl -- sh
# curl http://ingest-service:8080/actuator/health #will return 404 cause this path doesnt exits (havent exposed health endpoint)



# REBUILD AND DEPLOY

# docker build -t ingest-service:1.1 .
# kubectl rollout restart deployment ingest-service


# SCALING

# kubectl scale deployment ingest-service --replicas=5
# kubectl get pods


# Stop the ingest-service
# kubectl scale deployment ingest-service --replicas=0
