apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-service
  template:
    metadata:
      labels:
        app: ingest-service
    spec:
      containers:
        - name: ingest-service
          image: ingest-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"

# kubectl apply -f ingest-deployment.yaml
# kubectl get pods